tasks/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'tasks'

urlpatterns = [
    path('', views.TaskListView.as_view(), name = 'task-list'),
    path('create/', views.TaskCreateView.as_view(), name = 'task-create'),
    path('<int:pk>/delete/', views.TaskDeleteView.as_view(), name = 'task-delete'),
    path('<int:pk>/update/', views.TaskUpdateView.as_view(), name = 'task-update'),

]

todolist/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from tasks import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.LandingPage.as_view(), name='landing-page'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('tasks/', include('tasks.urls', namespace='tasks')),
]

tasks/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    pass


class Task(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField(max_length=100, blank=True, null=True)
    complete = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey('User', null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-id']

tasks/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UsernameField

from . import models

class ModelTaskForm(forms.ModelForm):

    class Meta:
        model = models.Task
        fields = (
            'title',
            'description',
        )


class ModelTaskUpdateForm(forms.ModelForm):
    class Meta:
        model = models.Task
        fields = (
            'title',
            'description',
            'complete'
        )    


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = models.User
        fields = ("username",)
        field_classes = {"username": UsernameField}

tasks/views.py
from django.views.generic import TemplateView, CreateView, UpdateView, ListView
from django.urls import reverse
from django.views.generic.edit import DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin

from . import models
from . import forms
# Create your views here.


class SignUpView(CreateView):
    template_name = './registration/signup.html'
    form_class = forms.CustomUserCreationForm

    def get_success_url(self) -> str:
        return reverse('login')

class LandingPage(TemplateView):
    template_name = './landing_page.html'


class TaskListView(LoginRequiredMixin, ListView):
    template_name = 'task_list.html'
    context_object_name = 'tasks'
   
    def get_queryset(self):
        queryset = models.Task.objects.filter(user = self.request.user.id, complete = False)
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)
        queryset = models.Task.objects.filter(
            complete = True,
            user = self.request.user.id
        )
        context.update({
            'completed_tasks': queryset
        })
        return context    


class TaskCreateView(LoginRequiredMixin, CreateView):
    template_name = 'task_create.html'
    form_class = forms.ModelTaskForm

    def form_valid(self, form):
        task = form.save(commit=False)
        task.user = self.request.user
        task.save()
        return super(TaskCreateView, self).form_valid(form)

    def get_success_url(self) -> str:
        return reverse('tasks:task-list')


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = models.Task
    template_name = 'task_delete.html'

    def get_success_url(self) -> str:
        return reverse('tasks:task-list')


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'task_update.html'
    form_class = forms.ModelTaskUpdateForm
    model = models.Task
    
    def get_success_url(self) -> str:
        return reverse('tasks:task-list')

tasks/templates/task_create.html
{% extends "base.html" %}
{% load tailwind_filters %}


{% block content %}
<div class = 'max-w-lg mx-auto mt-20'>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy}}
        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded" type="submit">Submit</button>
    </form>
</div>

{% endblock content %}

tasks/templates/task_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content %}

<div class = 'max-w-lg mx-auto mt-20'>
    <p>Are you sure you want to delete this task?</p>

        <form method="POST">
            {% csrf_token %}
            {{ form }}
            <button class="flex text-white bg-red-600 border-0 py-2 px-6 focus:outline-none hover:bg-red-500 rounded">Delete</button>
        </form>    
</div>
{% endblock content %}

tasks/templates/task_list.html
{% extends "base.html" %}
{% block content %}



<section class="text-gray-600 body-font">
    <div class="container px-5 py-20 mx-auto">
      <div class="flex flex-col text-center w-full mb-20">
        <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">List of tasks</h1>
      </div>
      <div class="lg:w-2/3 w-full mx-auto overflow-auto">
        <table class="table-auto w-full text-left whitespace-no-wrap">
          <thead>
            <tr>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Complete</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Title</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Description</th>
              <th class="w-10 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tr rounded-br"></th>
            </tr>
          </thead>
          <tbody>
            
            {% for task in tasks %}
            <tr class="border border-grey-500">
                <td class="px-4 py-3"><a href="{% url 'tasks:task-update' task.pk %}"><svg class="w-6 h-6" fill="white" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg></td></a>
                <td class="px-4 py-3">{{ task.title }}</td>
                <td class="px-4 py-3 text-lg text-gray-900">{{ task.description }}</td>
                <td class="w-10 text-center">
                    <a href="{% url 'tasks:task-delete' task.pk %}" class="text-red-700 hover:text-red-800"><svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path></svg></a>
                </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="flex pl-4 mt-10 lg:w-2/3 w-full mx-auto">
        <a href="{% url 'tasks:task-create'%}" class="bg-transparent text-blue-700 font-semibold hover:text-blue-900 py-2 px-4">Add task</a>
      </div>

      <div class="lg:w-2/3 w-full mx-auto overflow-auto mt-20">
        <h2 class="sm:text-2xl text-2xl font-medium title-font mb-5 text-gray-900">Completed</h2>
        <table class="table-auto w-full text-left whitespace-no-wrap">
          <thead>
            <tr>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Complete</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Title</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Description</th>
              <th class="w-10 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tr rounded-br"></th>
            </tr>
          </thead>
          <tbody>

            {% for task in completed_tasks %}
            <tr class="border border-grey-500">
                <td class="px-4 py-3"><a href="{% url 'tasks:task-update' task.pk %}"><svg class="w-6 h-6" fill="green" stroke="white" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg></td></a>
                <td class="px-4 py-3">{{ task.title }}</td>
                <td class="px-4 py-3 text-lg text-gray-900">{{ task.description }}</td>
                <td class="w-10 text-center">
                    <a href="{% url 'tasks:task-delete' task.pk %}" class="text-red-700 hover:text-red-800"><svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path></svg></a>
                </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>


    </div>
  </section>


{% endblock content %}

tasks/templates/task_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class = 'max-w-lg mx-auto mt-20'>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy}}
        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded" type="submit">Submit</button>
    </form>
</div>

{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="theme-color" content="#000000"/>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <title>To Do List</title>
</head>
<body>
    {% include "components/nav.html" %}


    {% block content %}
    {% endblock content %}
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>



</body>

</html>

templates/components/nav.html
    <div class="relative bg-red-400">
        <div class="max-w-7xl mx-auto px-4 sm:px-6">
          <div class="flex justify-between  items-center py-6 md:justify-start md:space-x-10">
            <div class="flex justify-start lg:w-0 lg:flex-1">
              <a href="{% url 'landing-page' %}">
                <h1 class = ''>
                  <svg class="h-12 w-12 text-blue-500"  fill="none" viewBox="0 0 24 24" stroke="white">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01"/>
                  </svg>
                </h1>
              </a>
            </div>
            <nav class="md:flex space-x-10">
      
              <a href="{% url 'tasks:task-list' %}" class="text-base font-medium text-white hover:text-gray-900"> Tasks </a>
              <a href="#" class="text-base font-medium text-white hover:text-gray-900"> Link </a>
      
            </nav>
            
            <div class="md:flex items-center justify-end md:flex-1 lg:w-0">
        

              {% if request.user.is_authenticated %}
                    <p> You are logged as {{ request.user.username }}</p>
                    <a href = '{% url "logout" %}' class="ml-8 whitespace-nowrap inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-indigo-600 hover:bg-indigo-700">
                    Log out
                    <a/>
              {% else %}
            <a href="{% url 'login' %}" class="ml-8 whitespace-nowrap inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-indigo-600 hover:bg-indigo-700"> Log in </a>
            <a href="{% url 'signup' %}" class="ml-8 whitespace-nowrap inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-indigo-600 hover:bg-indigo-700"> Sign up </a>
              {% endif %}
              

            </div>
          </div>
        </div>
    </div>

templates/landing_page.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font relative">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-12">
      <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">Welcome to To do List</h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">Please log in, or sign up</p>
    </div>
    <form method="POST" action="login/" class="lg:w-1/2 md:w-2/3 mx-auto">
      {% csrf_token %}
      <div class="flex flex-wrap -m-2">
        <div class="p-2 w-1/2">
          <div class="relative">
            <label for="username" class="leading-7 text-sm text-gray-600">Username</label>
            <input type="text" name="username" class="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
          </div>
        </div>
        <div class="p-2 w-1/2">
          <div class="relative">
            <label for="password" class="leading-7 text-sm text-gray-600">Email</label>
            <input type="password" name="password" class="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
          </div>
        </div>

        <div class="p-2 w-full">
          <button class="log-in flex mx-auto text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg">Log-in</button>
        </div>

      </div>
    </form>
  </div>
</section>

{% endblock content %}
 